/* Generated by tools/build.cjs. Do not edit by hand. */
'use strict';
const VERSION = 'e7a38d0e07';
const CACHE = 'pdftoolkit-' + VERSION;
const PRECACHE = [
  "./",
  "compress/",
  "css/style.css",
  "delete/",
  "extract/",
  "fonts/bricolage-grotesque-latin-ext-wght-normal.woff2",
  "fonts/bricolage-grotesque-latin-wght-normal.woff2",
  "fonts/figtree-latin-ext-wght-normal.woff2",
  "fonts/figtree-latin-wght-normal.woff2",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "images-to-pdf/",
  "js/app.js",
  "js/config.js",
  "js/i18n.js",
  "js/lang/fil.js",
  "js/tools-meta.js",
  "manifest.webmanifest",
  "merge/",
  "pdf-to-images/",
  "reorder/",
  "rotate/",
  "split/",
  "vendor/jszip.min.js",
  "vendor/pdf-lib.min.js",
  "vendor/pdf.min.js",
  "vendor/pdf.worker.min.js",
  "watermark/"
];

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('pdftoolkit-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  /* Pages: try the network first so updates show up, fall back to the cache when offline. */
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).then(res => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
        return res;
      }).catch(() => caches.match(req).then(hit => hit || caches.match('./')))
    );
    return;
  }

  /* Everything else: use the cached copy, and refresh it in the background. */
  event.respondWith(
    caches.match(req).then(hit => {
      const refresh = fetch(req).then(res => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
        return res;
      }).catch(() => hit);
      return hit || refresh;
    })
  );
});
